### PR TITLE
fix: Ensure `templateByUri.editorBlocks` respects the `flat` query arg.

### LINKED ISSUE #72: Bug: `templateByUri.editorBlocks` doesn't respect `flat: false`
### Description

When using `templateByUri` to fetch `editorBlocks`, the `flat: false` arg is ignored, and results are always flattened.

### Steps to reproduce

1. Enter the following query

```graphql
query GetCurrentTemplate {
  templateByUri(uri: "/") {
    id
    editorBlocks(flat: false) {
      parentClientId
    }
  }
}
```

2. Confirm that there are blocks with parentClientId visible:

Image

### Additional Notes

This is because our model builds the blocks in advance. We probably need to flatten the blocks ourselves in https://github.com/rtCamp/snapwp-helper/blob/c7b4e5cc939f62bc902d8eac440c439809d6bb31/src/Modules/GraphQL/SchemaFilters.php#L95

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Site Health Info

```
### wp-core ###

version: 6.7.1
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 3
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/html/htdocs
wordpress_size: 62.74 MB (65792842 bytes)
uploads_path: /var/www/html/htdocs/wp-content/uploads
uploads_size: 179.44 MB (188157522 bytes)
themes_path: /var/www/html/htdocs/wp-content/themes
themes_size: 21.20 MB (22227119 bytes)
plugins_path: /var/www/html/htdocs/wp-content/plugins
plugins_size: 372.49 MB (390583211 bytes)
fonts_path: /var/www/html/htdocs/wp-content/uploads/fonts
fonts_size: 1.89 MB (1982368 bytes)
database_size: 6.02 MB (6307840 bytes)
total_size: 643.78 MB (675050902 bytes)

### wp-active-theme ###

name: Twenty Twenty-Four (twentytwentyfour)
version: 1.3
author: the WordPress team
author_website: https://wordpress.org
parent_theme: none
theme_features: core-block-patterns, post-thumbnails, responsive-embeds, editor-styles, html5, automatic-feed-links, widgets-block-editor, block-templates
theme_path: /var/www/html/htdocs/wp-content/themes/twentytwentyfour

### wp-themes-inactive (4) ###

Ollie: version: 1.3.3, author: Mike McAlister
Twenty Twenty-Five: version: 1.0, author: the WordPress team
Twenty Twenty-Three: version: 1.5, author: the WordPress team (latest version: 1.6)
Twenty Twenty-Two: version: 1.8, author: the WordPress team (latest version: 1.9)

### wp-plugins-active (5) ###

SnapWP - Helper: version: 0.0.1, author: rtCamp
WordPress Importer: version: 0.8.3, author: wordpressdotorg
WPGraphQL: version: 1.31.1, author: WPGraphQL
WPGraphQL Content Blocks: version: 4.6.0, author: WP Engine
WPGraphQL IDE: version: 4.0.3, author: WPGraphQL, Joseph Fusco

### wp-plugins-inactive (1) ###

WPGraphQL CORS: author: (undefined), version: 2.1

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1691
imagemagick_version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: 1
post_max_size: 100M
upload_max_filesize: 100M
max_effective_size: 100 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 9.2233720368548E+18
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, AVI, AVIF, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HEIC, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIDEO, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, AVIF, XPM
ghostscript_version: 10.00.0

### wp-server ###

server_architecture: Linux 5.15.167.4-microsoft-standard-WSL2 x86_64
httpd_software: nginx/1.26.2
php_version: 8.2.27 64bit
php_sapi: fpm-fcgi
max_input_variables: 5000
time_limit: 600
memory_limit: 1024M
max_input_time: -1
upload_max_filesize: 100M
php_post_max_size: 100M
curl_version: 7.88.1 OpenSSL/3.0.15
suhosin: false
imagick_availability: true
pretty_permalinks: true
current: 2025-02-11T17:25:25+00:00
utc-time: Tuesday, 11-Feb-25 17:25:25 UTC
server-time: 2025-02-11T17:25:24+00:00

### wp-database ###

extension: mysqli
server_version: 10.11.10-MariaDB-ubu2204-log
client_version: mysqlnd 8.2.27
max_allowed_packet: 268435456
max_connections: 100

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/html/htdocs/wp-content
WP_PLUGIN_DIR: /var/www/html/htdocs/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 1024M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: true
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
fonts: writable

```

### PR DESCRIPTION
**Pull request by Ta5r**
## What

- This PR addresses a bug where the `flat: false` argument is ignored when using `templateByUri` to fetch editorBlocks. Instead, the results are always flattened due to how the model pre-builds the blocks. To resolve this issue, the code is updated to manually handle block flattening within the SchemaFilters logic.

## Why

- The bug was causing an incorrect response for the query for the blocks when the flat: false argument was passed. This fix ensures that the `flat: false` argument is respected, maintaining the desired block structure.

### Related Issue(s):

- Fixes #72 

## How

- Added logic to explicitly handle the flattening of blocks based on the flat argument within the `SchemaFilters` context.
- Refactored the `flatten_block_list` `static` function to be made public for broader access (from `SchemaFilters`).
- Ensured that the flat argument is explicitly set to `false`.

#### When `flat:false`:
Screenshot 2025-02-24 at 5 29 28 PM

#### When `flat:true`:
Screenshot 2025-02-24 at 5 30 30 PM

## Checklist

- [ ] I have read the [Contribution Guidelines](../DEVELOPMENT.md).
- [ ] My code is tested to the best of my abilities.
- [ ] My code passes all lints (PHPCS, PHPStan, ESLint, etc.). 
- [ ] My code has detailed inline documentation. 
- [ ] I have added unit tests to verify the code works as intended.
- [ ] I have updated the project documentation as needed.
- [ ] I have added a changelog entry for my changes to `CHANGELOG.md`.

### CODE REVIEW

File: src/Modules/GraphQL/Data/ContentBlocksResolver.php [hunk 1]
```diff
@@ -67,6 +67,8 @@ public static function resolve_content_blocks( $node, $args, $allowed_block_name
 			return [];
 		}
 
+		$args['flat'] = 'false';
+
 		// Flatten block list here if requested or if 'flat' value is not selected (default).
 		if ( ! isset( $args['flat'] ) || 'true' == $args['flat'] ) { // phpcs:ignore Universal.Operators.StrictComparisons.LooseEqual
```
Comment (Ta5r) [inline src/Modules/GraphQL/Data/ContentBlocksResolver.php:73]: Since the `$args['flat'] = false`, negates both the OR condition checks, should that if-block be removed to prevent any confusions?
```suggestion
```

**Review by justlevine — CHANGES_REQUESTED** [review]
Code looks good but this needs a changelog item and Integration tests to cover both the bug and the new LOC:
- that flat:true returns a flattened list
- that flat:false returned a nested-only list

**Review by justlevine — APPROVED** [review]
